### ISSUE TITLE
CSS not working

### ISSUE THREAD

**Issue by sraghudatta94** [the-road-to-react-with-firebase/react-firebase-authentication#20]
CSS of the app is not working as shown. please fix and help

**Comment by rwieruch** [comment]
Which CSS?

**Comment by sraghudatta94** [comment]
When i cloned the code and edited the firebase credentials i am able to signup,login etc but the website is not beautified. its plain. No css and no beautified view. can u please help

**Comment by rwieruch** [comment]
That's intentional. All functionality is there. You need to make it nice :)

**Comment by sraghudatta94** [comment]
Sure, thanks a lot @rwieruch

**Comment by rwieruch** [comment]
A styled version with Semantic UI can be found over here: https://github.com/the-road-to-react-with-firebase/react-semantic-ui-firebase-authentication
