### ISSUE TITLE
Component labelled SignUpForm instead of SignUpFormBase

### ISSUE THREAD

**Issue by aviginsburg** [the-road-to-react-with-firebase/react-firebase-authentication#27]
Hi Robert, 

The book is brilliant! Keep up the amazing work! A quick question/issue, on Page 33 of the book in the <code>src/components/SignUp/index.js</code> the component is labelled **SignUpForm** though I believe this should actually be **SignUpFormBase** (from the alterations made higher up the page).

Happy to be wrong!

**Comment by rwieruch** [comment]
You are totally right! I have already fixed it for the next edition of the book :) Thanks for reporting it though!
