### ISSUE TITLE
error of: A continue URL must be provided in the request.

### ISSUE THREAD

**Issue by eldyvoon** [the-road-to-react-with-firebase/react-firebase-authentication#28]
Got message of 

```A continue URL must be provided in the request.```

after done signup.

**Comment by rwieruch** [comment]
What was the mistake here @eldyvoon :)

**Comment by eldyvoon** [comment]
I missed this in .env

REACT_APP_CONFIRMATION_EMAIL_REDIRECT=http://localhost:3000
