### ISSUE TITLE
Security rules format

### ISSUE THREAD

**Issue by iryhor** [the-road-to-react-with-firebase/react-firebase-authentication#29]
The format of the security rules seems to be in the format of Firebase Realtime Database, not in the "match" syntax of Cloud Firestore.

**Comment by rwieruch** [comment]
Yes, there is an issue for it: https://github.com/the-road-to-react-with-firebase/react-firestore-authentication/issues/10 Do you mind tackling it? :)

**Comment by iryhor** [comment]
I responded on that issue thread, but I haven't collaborated to an open source project before so I'm just attached the code to my response.   Apologies for the noobiness.
