### ISSUE TITLE
Firebase Auth Error

### ISSUE THREAD

**Issue by MaxiCB** [the-road-to-react-with-firebase/react-firebase-authentication#36]
Within the App class this.props.firebase.auth.onAuthStateChanged needs to be updated to this.props.firebase.auth().onAuthStateChanged to avoid errors.

**Comment by kimothokamau** [comment]
I'm also getting this error and changing to auth() has not yet fixed it. Will update when I find a fix.

> TypeError: Cannot read property 'auth' of null
WithAuthentication.componentDidMount

**Comment by Issam-AB** [comment]
yes i'm also getting this error I don't know what to do to solve this problem
  

>  TypeError: this.props.firebase.doCreateUserWithEmailAndPassword is not a function
>     at SignUpFormBase.onSubmit
